### ISSUE TITLE
Collection tree and managing series/issue records

### ISSUE THREAD

**Issue by SaschaAdler** [crkn-rcdr/CIHM-Meta#33]
By my estimation, the collection tree looks something like this:

```
       online
       / | \
      /  |  \
     /   |   \
    /    |    \
   /     |     \
  /      |      \
monog serials govpubs
       / | \
      /  |  \
     /   |   \
    /    |    \
  per  annual news
```

Conceivably, the `heritage` and `online` collections can also be added to the currently-only-a-placeholder `canadiana` collection, but this wouldn't have any public effect. I don't think it makes sense to bother with ensuring `eco` subcollections are children of `eco`, both because they aren't currently public, and because `per` has had contributions but none of the rest have.

We can implement this tree in the collection database by ensuring that e.g. if a series record has been tagged with `online`, `serials`, and `annual`, it should only be added to the `annual` collection.

In addition, issue records should only be children of their parent series records.

If it doesn't do so already, Hammer/Press can walk up the collection tree to figure out what collection tags each cosearch/copresentation record should have.

**Comment by RussellMcOrmond** [comment]
First step is to run `loadseries` and Smelter to add in all the manifests and collections that have changed since we last ran things.

**Comment by RussellMcOrmond** [comment]
A different thought.

In `accessor` we will want a function that will handle this correctly, looking up parents in the view.  (IE: If `per` is in, that `serials` and `online` aren't also added in).

That function could accept an array of collections which a given `noid` should be added to.  The special case of an empty array would simply confirm the tree is correct.   The function would only store `members` if there was a change to a given collection.

I'm assuming that if a noid is in `serials` that if it is added to `per` that it would then be removed from `serials`, and thus it isn't only the document of the specific collection that might be modified.



The database conversion tool for this ticket would then just grab all noids, and loop through them calling `accessor` appropriately.  It would keep a local database of completed noids so that it could restart, as it is expected that running this would take time.  Rather than writing the algorithm in two languages, we would be writing it in one and testing from the other.  We don't need to worry about the REST interface as long as there is a small CLI to call the appropriate API.

**Comment by RussellMcOrmond** [comment]
The `access` design document that includes the `members` view locked up again over the weekend, and I forced it to re-build.  I think we'll want to do something on this issue sooner rather than later, so confirm that the size of the members list is the underlying problem.

I'll write a tool that uses https://admin-dev.canadiana.ca/couchview/access/tree/members?group=2&range=false&reduce=true to display the slug name and count for the 29 unordered collections.

There will still be large members lists for some ordered collections -- some of the newspapers have a very large number of issues (69429/s0js9h41kt84= oocihm.N_00367  has 12317 members).  Not sure if this is the intention in the future.  Managing these large ordered collections will need to be tested with the tools.

The sooner the management tools are ready, the sooner the teams will be able to think in terms of better arrangements than what they have been able to do with collection tags and series records.

**Comment by RussellMcOrmond** [comment]
Sent a note to metadata and production team about some odd ID's found when doing a quick test de-duplicating the collection tree.

I set up a function to take all the members of online, and then subtract the members of the other 6 lists.
I also set up a function to take the members of serials, and subtract its 3 sub-collections.

I got unexpected results, as I assumed each would be empty.

**Comment by RussellMcOrmond** [comment]
While `loadseries` supports the collection tree, Hammer2 also needs to be updated.  This is temporarily waiting on a decision about whether a Perl-compatible API to https://github.com/crkn-rcdr/Access-Platform/tree/main/accessor will be used, or the functionality duplicated in Perl.
